add new function for sending to paw
pepfar-datim/datapackr-app pull request #110
Opened 2024-02-23 18:12 UTC by flopez-bao

utilizing createDataExport to account for paw/datim divergence

### Related Issues
- DP-1198

2024-02-23 18:15 UTC, flopez-bao commented
will begin testing

2024-02-23 20:04 UTC, flopez-bao commented
testing was run in the following manner:
1. datapcks from this [folder](https://pepfar.sharepoint.com/:f:/r/sites/PRIMEInformationSystems/Shared%20Documents/COP24%20Systems%20Support/Target%20Setting%20Tool%20(Data%20Pack)/E2E%20Testing%20files?csf=1&web=1&e=hcZffE) were validated in the app branch 
2. flatpacks were downloaded and sent to christian for check - passed
3. data was sent to S3 test to test:
4. data was read back to make sure Y2 was empty as expected:


`##### get paw data that was sent to S3 ----
d <- list()
d$info$cop_year <- 2024
d$info$sane_name <- "Cameroon"

object_name <- paste0("datim_export/",gsub("^20", "cop",d$info$cop_year),
                      ifelse(d$info$cop_year==2021,"_opu",""),
                      "/",d$info$sane_name,".csv")

s3 <- paws::s3()

r <- tryCatch({
  s3_download <- s3$get_object(Bucket = Sys.getenv("AWS_S3_BUCKET"),
                               Key = object_name
                               )
  futile.logger::flog.info("DATIM Export read from S3", name = "datapack")
  TRUE
},
error = function(err) {
  futile.logger::flog.info("DATIM Export could not be read from S3", name = "datapack")
  futile.logger::flog.info(err, name = "datapack")
  FALSE
})


# write output to file
writeBin(s3_download$Body, con = "Cameroon.csv")
cameroon <- read.csv("Cameroon.csv", sep = "|")

##### get paw data year2 was sent to S3 ----
object_name <- paste0("datim_export/",gsub("^20", "cop",d$info$cop_year),
                      ifelse(d$info$cop_year==2021,"_opu",""),
                      "/",d$info$sane_name,"_Y2",".csv")

s3 <- paws::s3()

r <- tryCatch({
  s3_download <- s3$get_object(Bucket = Sys.getenv("AWS_S3_BUCKET"),
                               Key = object_name
  )
  futile.logger::flog.info("DATIM Export read from S3", name = "datapack")
  TRUE
},
error = function(err) {
  futile.logger::flog.info("DATIM Export could not be read from S3", name = "datapack")
  futile.logger::flog.info(err, name = "datapack")
  FALSE
})


# write output to file
writeBin(s3_download$Body, con = "Cameroon_Y2.csv")
cameroon_y2 <- read.csv("Cameroon_Y2.csv", sep = "|")`



![image](https://github.com/pepfar-datim/datapackr-app/assets/92821116/42381aae-5d9d-43cd-965b-f3459b604122)

2024-02-23 20:14 UTC, JordanBalesBAO approved these changes

2024-02-26 13:59 UTC, jason-p-pickering requested changes
@christian-domaas @flopez-bao  This change alters the output of the FlatPack export to mirror what is being sent to PAW as opposed to what is being sent to DATIM. I am not sure this is super-important, as this is the tab with the "export" format (not the analytics table). I just wanted to to double check that this was an intentional change. 

The change in `sendDATIMExportToS3` looks fine but maybe we should rename this to `sendPAWExportToS3` to enhanced clarity.

2024-02-26 14:21 UTC, jason-p-pickering approved these changes

2024-02-26 14:21 UTC, merged